[theme]
primaryColor = "#718E88"
backgroundColor = "#F7F8F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#26343B"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
